### ISSUE TITLE
Getting Error 404 for repository first tag

### ISSUE THREAD

**Issue by weslleyss12** [escaletech/circleci-gh-conventional-release#1]
Orb Version: 0.1.0

### Describe the bug

When you run this orb on a repository without a previous tag, it's returning a 404 error since it's trying to compare the current tag to the previous one that doesn't exist.

### Steps to reproduce

1. Create or use any Github repository that doesn't have any tag/release
2. Push a brand new tag and run this orb

### Expected behavior

1. Identify if exist or not a previous tag
2. In the case of being the first time, apply the diff based on the first repository commit

### Actual behavior

Trying to do a GET on a URL that doesn't exist. (https://api.github.com/repos/escaletech/health-socrates/compare/...v1.0.0)

![image](https://user-images.githubusercontent.com/8439154/86279639-bb588400-bbb0-11ea-8e9a-32b50f17c452.png)
![image](https://user-images.githubusercontent.com/8439154/86279712-d88d5280-bbb0-11ea-873a-32e93667d25c.png)

**Comment by rdumont** [comment]
Alright, this is pretty straightforward. Looks like you've given all the necessary details.
