### ISSUE TITLE
Getting a 404 when trying to POST a new release

### ISSUE THREAD

**Issue by weslleyss12** [escaletech/circleci-gh-conventional-release#2]
Orb Version: 0.1.0

### Describe the bug

Getting 404 when trying to POST a new release with Github API when the `Escale CI Bot` is not a member of the repository.

### Steps to reproduce

1. Create or use a Github repository which doesn't have the `Escale CI Boot` as a member
2. Publish a new tag on a repository that already has a previous one

### Expected behavior

1. Orb/Project documentation informing that we have to add the `Escale CI Boot` to the repository
2. Circle CI Job get the differences between the current tag and the previous one
3. Publish a new release for the current tag with the obtained information

### Actual behavior

1. Getting a 404 when trying to POST the information
2. Don't provide a clear feedback of what is the root cause

![image](https://user-images.githubusercontent.com/8439154/86282465-ac280500-bbb5-11ea-8525-f548e204dedb.png)

### Proposal

1. Update documentation to include `Escale CI Bot` as a repository member 
2. Update the error feedback

**Comment by rdumont** [comment]
Thanks for the feedback!

What I think should be done is to output some error message saying:

```
GitHub API returned 404 Not Found when creating the new release. Some common causes for this might be:
1. The GitHub API token is either missing or invalid
2. The user that the API token belongs to doesn't have sufficient permissions on the repository. Please make sure that they are at least a "Maintainer".
```

I disagree about mentioning one user specifically, such as Escale CI Bot because that is just the way we are doing it in one special context.

**Comment by weslleyss12** [comment]
Nice, if we put something like this will make it easier to identify the problem :D
And I do agree with the Escale CI Bot observation since you can pass the params specified on readme.
